on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * *"

name: Check for metadata json changes

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
    
      # Install R and dependencies
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release' # The R version to download (if necessary) and use.
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            censusapi

      # Run R script to grab metadata and compare against saved .csv
      - name: Run update-metadata.R
        run: Rscript scripts/update-metadata.R

      # Compare the response to the previous run, using a hash of the response as the cache key
      - name: Compare cached endpoints.csv
        id: cache
        uses: actions/cache@v4
        with:
          path: data/endpoints.csv
          key: ${{ hashFiles('data/endpoints.csv') }}

      - name: If the cached CSV and new are identical, do nothing
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          echo "endpoints.csv did not change"

      - name: If the cached CSV has changed, commit update
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "endpoints.csv changed"

          # Update timestamp in update-time.txt
          echo "$(TZ=:America/New_York date)" > update-time.txt

          # Configure git user
          git config user.name "hrecht[bot]"
          git config user.email "9753760+hrecht[bot]@users.noreply.github.com"

          # Commit files
          git add .
          timestamp=$(TZ=:America/New_York date)
          git commit -m "Update data ${timestamp}" || exit 0
          git push
