on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * *"

name: Check for metadata json changes

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
    
      # Use cURL to fetch the given URL, saving the response to `data.json`
      #- name: Fetch data
      #  run: curl "https://api.census.gov/data.json" -o data/data.json
          
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release' # The R version to download (if necessary) and use.
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            censusapi
      - run: Rscript scripts/update-metadata.R

      # Compare the response to the previous run, using a hash of the response as the cache key
      - name: Fetch cached endpoints.csv
        id: cache
        uses: actions/cache@v4
        with:
          path: data/endpoints.csv
          key: ${{ hashFiles('data/endpoints.csv') }}

      - name: Testing cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "something changed"

      - name: Testing cache 2
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          echo "something did not change"

      - name: If data has changed, commit
        run: |
          # Update timestamp in update-time.txt
          echo "$(TZ=:America/New_York date)" > update-time.txt

          # Configure git user
          git config user.name "hrecht[bot]"
          git config user.email "9753760+hrecht[bot]@users.noreply.github.com"

          # Commit files
          git add .
          timestamp=$(TZ=:America/New_York date)
          git commit -m "Update data ${timestamp}" || exit 0
          git push
