on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * *"

name: Check for metadata json changes

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
    
      # Install R and dependencies
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release' # The R version to download (if necessary) and use.
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            censusapi

      # Run R script to grab metadata and compare against saved .csv
      - name: Run update-metadata.R
        run: Rscript scripts/update-metadata.R

      # Commit or not based on env variable passed from R
      - name: If the cached CSV has not changed, do nothing
        #if: "$UPDATED_DATA" == false
        run: |
          echo "endpoints.csv changed:" $UPDATED_DATA

          # GITHUB_ENV var set in R script
          printf '%s\n' "$UPDATED_DATA"

      - name: If the cached CSV has changed, commit update
        if: "$UPDATED_DATA" == true
        run: |
          echo "endpoints.csv changed:" $UPDATED_DATA

          # GITHUB_ENV var set in R script
          printf '%s\n' "$UPDATED_DATA"

          # Configure git user
          git config user.name "hrecht[bot]"
          git config user.email "9753760+hrecht[bot]@users.noreply.github.com"

          # Commit files
          git add .
          timestamp=$(TZ=:America/New_York date)
          git commit -m "Update data ${timestamp}" || exit 0
          git push
